<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net11.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>15.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ProjNET" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DDjourneys.Tracking.Tests" />
  </ItemGroup>

</Project>
