using System.Text.Json.Serialization;

namespace DDjourneys.Core.Providers.Vvo.Models;

/// <summary>
/// Represents a VVO trip planning response.
/// </summary>
public sealed class VvoTripResponse
{
	[JsonPropertyName("Status")]
	public VvoStatus? Status { get; init; }


	[JsonPropertyName("SessionId")]
	public string? SessionId { get; init; }


	[JsonPropertyName("Routes")]
	public IReadOnlyList<VvoRoute> Routes { get; init; }
		= Array.Empty<VvoRoute>();
}


/// <summary>
/// Represents one complete journey option returned by VVO.
/// </summary>
public sealed class VvoRoute
{
	[JsonPropertyName("RouteId")]
	public int RouteId { get; init; }


	[JsonPropertyName("Price")]
	public string? Price { get; init; }


	[JsonPropertyName("PriceDayTicket")]
	public string? PriceDayTicket { get; init; }


	[JsonPropertyName("TicketNotes")]
	public string? TicketNotes { get; init; }


	[JsonPropertyName("Net")]
	public string? Net { get; init; }


	[JsonPropertyName("NumberOfFareZones")]
	public string? NumberOfFareZones { get; init; }


	[JsonPropertyName("NumberOfFareZonesDayTicket")]
	public string? NumberOfFareZonesDayTicket { get; init; }


	[JsonPropertyName("FareZoneNames")]
	public string? FareZoneNames { get; init; }


	[JsonPropertyName("FareZoneNamesDayTicket")]
	public string? FareZoneNamesDayTicket { get; init; }


	[JsonPropertyName("FareZoneOrigin")]
	public int? FareZoneOrigin { get; init; }


	[JsonPropertyName("FareZoneDestination")]
	public int? FareZoneDestination { get; init; }


	[JsonPropertyName("Duration")]
	public int Duration { get; init; }


	[JsonPropertyName("Interchanges")]
	public int Interchanges { get; init; }


	[JsonPropertyName("RouteCancelled")]
	public bool RouteCancelled { get; init; }


	[JsonPropertyName("MotChain")]
	public IReadOnlyList<VvoMot> MotChain { get; init; }
		= Array.Empty<VvoMot>();


	[JsonPropertyName("PartialRoutes")]
	public IReadOnlyList<VvoPartialRoute> PartialRoutes { get; init; }
		= Array.Empty<VvoPartialRoute>();


	[JsonPropertyName("MapData")]
	public IReadOnlyList<string> MapData { get; init; }
		= Array.Empty<string>();
}


/// <summary>
/// Represents one partial route returned by VVO.
///
/// A partial route with regular stops is a movement segment.
/// Transfer/accessibility partial routes may have no regular stops.
/// </summary>
public sealed class VvoPartialRoute
{
	[JsonPropertyName("PartialRouteId")]
	public int PartialRouteId { get; init; }


	[JsonPropertyName("Duration")]
	public int Duration { get; init; }


	[JsonPropertyName("TripCancelled")]
	public bool TripCancelled { get; init; }


	[JsonPropertyName("ChangeoverEndangered")]
	public bool ChangeoverEndangered { get; init; }


	[JsonPropertyName("Infos")]
	public IReadOnlyList<string> Infos { get; init; }
		= Array.Empty<string>();


	[JsonPropertyName("BookingLink")]
	public string? BookingLink { get; init; }


	[JsonPropertyName("Mot")]
	public VvoMot? Mot { get; init; }


	[JsonPropertyName("RegularStops")]
	public IReadOnlyList<VvoStop> RegularStops { get; init; }
		= Array.Empty<VvoStop>();


	[JsonPropertyName("MapDataIndex")]
	public int MapDataIndex { get; init; } = -1;
}


/// <summary>
/// Represents transport information for a VVO partial route.
/// </summary>
public sealed class VvoMot
{
	/// <summary>
	/// Public line name displayed to passengers.
	/// </summary>
	[JsonPropertyName("Name")]
	public string? Name { get; init; }


	/// <summary>
	/// Provider transport type.
	/// </summary>
	[JsonPropertyName("Type")]
	public string? Type { get; init; }


	/// <summary>
	/// Final destination of this service.
	/// </summary>
	[JsonPropertyName("Direction")]
	public string? Direction { get; init; }


	/// <summary>
	/// VVO internal line identifier information.
	/// </summary>
	[JsonPropertyName("Diva")]
	public VvoDiva? Diva { get; init; }


	/// <summary>
	/// Transport operator name.
	/// </summary>
	[JsonPropertyName("TransportationCompany")]
	public string? TransportationCompany { get; init; }


	/// <summary>
	/// Operator identifier.
	/// </summary>
	[JsonPropertyName("OperatorCode")]
	public string? OperatorCode { get; init; }


	/// <summary>
	/// Human-readable product category.
	/// </summary>
	[JsonPropertyName("ProductName")]
	public string? ProductName { get; init; }


	/// <summary>
	/// Vehicle or service number assigned by the operator.
	/// </summary>
	[JsonPropertyName("TrainNumber")]
	public string? TrainNumber { get; init; }


	/// <summary>
	/// VVO data link identifier.
	/// </summary>
	[JsonPropertyName("DlId")]
	public string? DlId { get; init; }


	/// <summary>
	/// Provider-independent identifier generated by VVO.
	/// </summary>
	[JsonPropertyName("StatelessId")]
	public string? StatelessId { get; init; }


	/// <summary>
	/// Realtime passenger load reported for this service.
	/// </summary>
	[JsonPropertyName("Occupancy")]
	public string? Occupancy { get; init; }


	/// <summary>
	/// VVO disruption identifiers attached to this movement.
	/// </summary>
	[JsonPropertyName("Changes")]
	public IReadOnlyList<string> Changes { get; init; }
		= Array.Empty<string>();
}


/// <summary>
/// Represents VVO line identity information.
/// </summary>
public sealed class VvoDiva
{
	[JsonPropertyName("Network")]
	public string? Network { get; init; }


	[JsonPropertyName("Number")]
	public string? Number { get; init; }
}


/// <summary>
/// Represents one stop in a VVO journey leg.
/// </summary>
public sealed class VvoStop
{
	[JsonPropertyName("DataId")]
	public string? DataId { get; init; }


	[JsonPropertyName("Name")]
	public string? Name { get; init; }


	[JsonPropertyName("Place")]
	public string? Place { get; init; }


	[JsonPropertyName("Type")]
	public string? Type { get; init; }


	[JsonPropertyName("Platform")]
	public VvoPlatform? Platform { get; init; }


	[JsonPropertyName("ArrivalTime")]
	public DateTimeOffset? ArrivalTime { get; init; }


	[JsonPropertyName("DepartureTime")]
	public DateTimeOffset? DepartureTime { get; init; }


	[JsonPropertyName("ArrivalRealTime")]
	public DateTimeOffset? ArrivalRealTime { get; init; }


	[JsonPropertyName("DepartureRealTime")]
	public DateTimeOffset? DepartureRealTime { get; init; }


	[JsonPropertyName("ArrivalState")]
	public string? ArrivalState { get; init; }


	[JsonPropertyName("DepartureState")]
	public string? DepartureState { get; init; }


	[JsonPropertyName("Occupancy")]
	public string? Occupancy { get; init; }


	[JsonPropertyName("Latitude")]
	public double Latitude { get; init; }


	[JsonPropertyName("Longitude")]
	public double Longitude { get; init; }
}


/// <summary>
/// Represents a VVO platform/track object.
/// </summary>
public sealed class VvoPlatform
{
	[JsonPropertyName("Name")]
	public string? Name { get; init; }


	[JsonPropertyName("Type")]
	public string? Type { get; init; }
}