<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	  <TargetFrameworks>net11.0-android;net11.0-windows10.0.26100.0</TargetFrameworks>

	  <!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>DDjourneys</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>15.0</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>


		<!-- Display name -->
		<ApplicationTitle>DDjourneys</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.ddjourneys</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>MSIX</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">10.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">17.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<AssemblyTitle>DDjourneys</AssemblyTitle>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net11.0-android|AnyCPU'">
	  <ApplicationId>dev.Scharkenberg.DDjourneys</ApplicationId>
	  <ApplicationDisplayVersion>0.4.2</ApplicationDisplayVersion>
	  <ApplicationVersion>35</ApplicationVersion>
	  <EmbedAssembliesIntoApk>True</EmbedAssembliesIntoApk>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net11.0-windows10.0.26100.0|AnyCPU'">
	  <ApplicationId>dev.Scharkenberg.DDjourneys</ApplicationId>
	  <ApplicationDisplayVersion>0.4.2</ApplicationDisplayVersion>
	  <ApplicationVersion>35</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net11.0-android|AnyCPU'">
	  <ApplicationId>dev.Scharkenberg.DDjourneys</ApplicationId>
	  <ApplicationDisplayVersion>0.4.2</ApplicationDisplayVersion>
	  <ApplicationVersion>35</ApplicationVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net11.0-windows10.0.26100.0|AnyCPU'">
	  <ApplicationId>dev.Scharkenberg.DDjourneys</ApplicationId>
	  <ApplicationDisplayVersion>0.4.2</ApplicationDisplayVersion>
	  <ApplicationVersion>35</ApplicationVersion>
	</PropertyGroup>

  <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net11.0-android|AnyCPU'">
	<MauiIcon Include="Resources\AppIcon\appiconbg.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#F2C43D">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</MauiIcon>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net11.0-android|AnyCPU'">
	<MauiIcon Include="Resources\AppIcon\appiconbg.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#F2C43D">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</MauiIcon>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net11.0-windows10.0.26100.0|AnyCPU'">
	<MauiIcon Include="Resources\AppIcon\appicon_windows.svg" Color="#EAB62C">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</MauiIcon>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net11.0-windows10.0.26100.0|AnyCPU'">
	<MauiIcon Include="Resources\AppIcon\appicon_windows.svg" Color="#EAB62C">
	  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	</MauiIcon>
  </ItemGroup>

  <ItemGroup>
		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" BaseSize="222,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="CommunityToolkit.Maui" Version="15.0.1" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="11.0.0-*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\DDjourneys.Core\DDjourneys.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Pages\ThemesPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

</Project>
