namespace DDjourneys.Localization;

public sealed class EnglishUiStrings : IUiStrings
{
	public CommonStrings Common { get; } = new()
	{
		Ok = "OK",
		Cancel = "Cancel",
		Retry = "Try again",
		Close = "Close",
		Loading = "Loading",
		Searching = "Searching",
		Today = "Today",
		Tomorrow = "Tomorrow",
		Unknown = "Unknown",
		SearchAgain = "Search again",
		TryAgain = "Try again",
		Share = "Share",
		Search = "Search",
		Clear = "Clear",
		SearchFailed = "The search failed.",
		CouldNotReachService = "Could not reach the timetable service.",
		SomethingWentWrong = "Something went wrong.",
		NavigationError = "Navigation error.",
		CouldNotOpenJourney = "Could not open journey."
	};

	public PlanStrings Plan { get; } = new()
	{
		Title = "Where to?",
		FromPlaceholder = "From",
		ToPlaceholder = "To",
		ChooseStart = "Choose start",
		ChooseDestination = "Choose destination",
		ToggleFavouriteFrom = "Toggle favourite for start",
		ToggleFavouriteTo = "Toggle favourite for destination",
		SwapDescription = "Swap start and destination",
		Swap = "\u21c5",
		SearchJourneys = "Search journeys",
		Departure = "Leave",
		Arrival = "Arrive by",
		Date = "Date",
		Time = "Time",
		LeaveNow = "Now",
		Favourites = "Favourites",
		Recent = "Recent places",
		RecentSearches = "Recent searches",
		ShowAllSearches = "Show all {0}",
		ShowFewer = "Show fewer",
		ForgetSearch = "Remove this search",
		SearchAgain = "Search this connection again",
		StartAndDestinationRequired = "Start and destination are required.",
		UseLocationFrom = "Use my location as start",
		UseLocationTo = "Use my location as destination",
		GoHome = "Go home",
		SetHome = "Set home here",
		SaveRoute = "Save route",
		RouteNamePrompt = "Name for this route",
		SavedRoutes = "Saved routes",
		ForgetSavedRoute = "Remove saved route",
		LocationPermissionDenied = "Location access is needed to use your position.",
		LocationUnavailable = "Your position could not be determined.",
		NoStopNearby = "No stop found near your position.",
		Via = "Via",
		AddVia = "Add stop over",
		ClearVia = "Remove stop over",
		PlacesYouSearchForWillAppearHere =
			"Places you search for will appear here."
	};

	public DeparturesStrings Departures { get; } = new()
	{
		Title = "Departures",
		Stop = "Stop",
		ChooseStop = "Choose a stop",
		DeparturesTab = "Departures",
		ArrivalsTab = "Arrivals",
		Now = "Now",
		NoDepartures = "No departures found.",
		Lines = "Lines at this stop",
		ShowLines = "Show lines",
		HideLines = "Hide lines",
		Nearby = "Stops near you",
		UseMyLocation = "Use my location",
		TariffZone = "Tariff zone {0}",
		Metres = "{0} m",
		Cancelled = "Cancelled",
		RouteChanges = "Route changes affect this departure",
		Refresh = "Refresh",
		Updated = "Updated {0}",
		Hint = "Choose a stop to see what leaves next.",
		RunTitle = "Course",
		NoRun = "No course available for this departure.",
		VehicleHere = "Vehicle is here",
		OpenDepartures = "Departures at this stop"
	};

	public DisruptionsStrings Disruptions { get; } = new()
	{
		Title = "Disruptions",
		OnlyShortTerm = "Short-term only",
		FilterPlaceholder = "Filter by line",
		None = "No route changes.",
		Planned = "Planned",
		ShortTerm = "Short-term",
		AffectsRouting = "Considered in journey planning",
		From = "From {0}",
		Until = "Until {0}",
		Range = "{0} \u2013 {1}",
		Notices = "Notices",
		ShowAll = "Show all changes",
		Selected = "Showing the changes of the selected departure.",
		Refresh = "Refresh",
		Details = "Details"
	};

	// <extras>
	public ExtrasStrings Extras { get; } = new()
	{
		KindStop = "Stop",
		KindAddress = "Address",
		KindPoi = "Point of interest",
		SearchAddresses = "Addresses",
		SearchAddressesDescription = "Find addresses in the place search. The route includes the walk to the nearest stop.",
		SearchPois = "Points of interest",
		SearchPoisDescription = "Find landmarks, buildings and other places by name.",
		ExactPosition = "Start at my exact position",
		ExactPositionDescription = "\"Use my location\" picks the address you are at instead of the nearest stop.",
		LiveTitle = "Live vehicles",
		LiveShow = "Where is the vehicle?",
		LineFilterPlaceholder = "Line numbers, e.g. 11, 3 (empty: all)",
		LiveStart = "Show",
		LiveStop = "Stop",
		LiveConnecting = "Connecting…",
		LiveWaiting = "Waiting for vehicles…",
		LiveError = "The live positions are not available right now.",
		LiveLine = "Line {0}",
		LiveRun = "Run {0}",
		LiveSecondsAgo = "{0} s ago",
		LiveMinutesAgo = "{0} min ago",
		LiveOnTime = "On time",
		LiveSourceGps = "GPS",
		LiveSourceTelegram = "Radio telegram",
		LiveHint = "Positions come from the community TLMS network and can be incomplete.",
		LiveOpenMap = "Open map",
		AccessTitle = "Accessibility of this stop",
		AccessHide = "Hide accessibility",
		AccessNone = "The city publishes no accessibility data for this stop.",
		AccessPlatform = "Platform {0}",
		AccessBoarding = "Boarding: {0}",
		AccessKerb = "Kerb height: {0}",
		AccessWidth = "Width: {0}",
		AccessTactile = "Tactile guidance: {0}",
		AccessAudio = "Announcements: {0}",
		ServiceShow = "DVB service points nearby",
		ServiceHide = "Hide service points",
		ServiceNone = "No service points nearby.",
		ServiceNeedsPosition = "Choose a stop or use your location first.",
		CapLive = "Live vehicles",
		CapOpenData = "City open data",
		CapFares = "Fares",
		CapOptimisation = "Route optimisation",
		OptSection = "Optimise route for",
		OptFastest = "Fastest",
		OptFewestChanges = "Fewest changes",
		OptLeastWalking = "Least walking",
		OptLowestFare = "Lowest fare",
		OptNote = "Only the VVO (TRIAS) provider honours this choice; other providers always search for the fastest route.",
		FaresTitle = "Tickets and prices",
		PdfFailed = "The PDF could not be loaded. Details are in the log file diagnostics.log.",
		LiveHowTitle = "How it works",
		LiveHowText = "Type one or more line numbers separated by commas (for example 3, 11) or tap the lines below; leave the field empty to see every vehicle. Then tap Show: the vehicles appear on the map and in the list and move as new positions arrive. Tap a vehicle in the list to find it on the map.",
		LineFilterLabel = "Line numbers (optional)",
		LiveQuickLines = "Tram lines",
		LiveAllLines = "All lines",
		LiveInvalid = "Ignored, not a line number: {0}",
		LiveEmpty = "No positions received yet. Not every vehicle reports its position; try other lines or leave the field empty.",
		LiveCount = "{0} vehicles",
		MapTitle = "Map",
		MapShow = "Show on map",
		MapJourneyTitle = "Journey map",
		MapStopTitle = "Stops nearby",
		MapNoData = "There are no positions to show on a map for this item.",
		MapStart = "Start",
		MapEnd = "Destination",
		RunDeparted = "This vehicle has already left; its course is no longer available.",
		MapAutoFit = "Auto-fit",
		MapFitNow = "Show everything",
		MapInfo = "Map data",
		TrackFollowing = "Following line {0} {1}",
		TrackNotFound = "This run reports no position right now. It may not have started yet, or its vehicle sends no radio telegrams.",
		TrackShowAll = "Show all vehicles of the line",
		TrackOnlyThisRun = "Only this run is shown, with its whole course.",
		NoticeClose = "Close",
		NoticeImageFailed = "The image could not be loaded.",
		NoticeEmpty = "This notice has no further text.",
		NoticeLinkFailed = "This link could not be opened.",
		AroundTitle = "Around this stop",
		LinesTitle = "Lines at this stop",
		LinesCount = "{0} lines",
		ServiceTitle = "Service points",
		ServiceHint = "Ticket machines and customer centres near here",
		ServiceCount = "{0} nearby",
		AccessHint = "Boarding height, tactile guidance, audio information",
		MapSummary = "Stop, stops nearby and open sections on a map",
		LiveSummary = "Where the vehicles of a line are right now",
		HomeTitle = "Home",
		HomeNotSet = "Not set: tap to use the stop nearest to you"
	};
	// </extras>

	public PlaceSearchStrings PlaceSearch { get; } = new()
	{
		Title = "Choose place",
		SearchPlaceholder =
		"Station, stop or address",
		Hint =
		"Type a station, stop or address.",
		TypeAtLeastThreeCharacters =
		"Type at least 3 characters.",
		NoPlacesFound = "No places found.",
		Searching = "Searching...",
		CouldNotReachService =
		"Could not reach the timetable service. Check your connection.",
		SearchForPlace = "Search for a place"
	};

	public ResultsStrings Results { get; } = new()
	{
		Title = "Journeys",
		Loading = "Loading journeys...",
		NoConnections = "No journeys found for this time.",
		JourneysCouldNotBeDisplayed =
			"The journeys could not be displayed.",
		SearchServiceUnavailable =
			"Could not reach the timetable service.",
		PlacesNotUsable =
			"These places can't be used with the selected data provider. Please choose them again.",
		Refresh = "Refresh",
		Retry = "Try again",
		Previous = "Earlier",
		Next = "Later"
	};

	public JourneyStrings Journey { get; } = new()
	{
		LegEarlier = "Earlier alternative",
		LegLater = "Later alternative",
		LegNone = "No alternative found for this ride.",
		OpenPdf = "Open as PDF",
		AlternativeShown = "Showing an alternative connection. Search again to go back.",
		Title = "Journey",
		FollowJourney = "Follow journey",
		DeactivateTracking = "Pause tracking",
		Refresh = "Refresh",
		Notes = "Notes",
		NoRealtimeData = "No realtime data",
		ShareJourney = "Share journey",
		NotServed = "Stop cancelled",
		InProgress = "In progress",
		Cancelled = "Cancelled",
		CouldNotBeDisplayed =
			"This journey could not be displayed.",
		ShowOrHideIntermediateStops =
			"Show or hide intermediate stops",
		Walk = "Walk",
		ShareTitle = "Share journey",
		ShareAsText = "As text",
		ShareAsImage = "As image",
		HandOff = "Use this journey",
		HandOffFailed = "The journey could not be passed to the other app.",

		Direct = "Direct",
		OneTransfer = "1 transfer",
		MultipleTransfers = "{0} transfers",
		OneNotice = "1 notice",
		MultipleNotices = "{0} notices",
		AccessibilitySummary =
			"Departs {0}, arrives {1}, {2}, {3}",
		AccessibilityCancelled = ", cancelled",
		AccessibilityArrivalDelay = ", arrival {0}",
		AccessibilityNotices = ", {0}",

		HideStops = "Hide stops",
		OneStop = "1 stop",
		MultipleStops = "{0} stops",
		To = "to",
		ContinueFrom = "continue from",
		ImmediateChange = "Immediate change",
		ToChange = "to change",
		WalkAbout = "Walk about",
		BetweenStops = "between stops",
		ConnectionMayBeMissed = "Connection may be missed",
		ConnectionGuaranteed = "Guaranteed connection: the next vehicle waits",
		NotPossible = "Not possible",
		BlockRideCancelled = "Line {0} is cancelled",
		BlockNotServed = "{0} is not served",
		BlockConnection = "Connection at {0} cannot be reached",
		ConnectionUnreachable = "Connection cannot be reached",
		ChangeAt = "Change at",
		Platform = "Platform",
		WithinStop = "within the stop",
		Track = "Track",
		LowFloor = "Low floor",
		WheelchairAccessible = "Wheelchair accessible",
		BicycleAccessible = "Bicycle accessible",
		Depart = "depart",
		Arrive = "arrive",
		ShowMore = "Show more",
		ShowLess = "Show less",
		ShowFullNotice = "Show the full notice",
		ShowLessNotice = "Show less of the notice",
		Warning = "Warning",
		Notice = "Notice",
		OnTime = "On time",

		// Occupancy strings
		Occupancy = "Occupancy",
		OccupancyVeryLow = "Very few passengers",
		OccupancyLow = "Few passengers",
		OccupancyMedium = "Moderate",
		OccupancyHigh = "Many passengers",
		OccupancyFull = "Full",
		OccupancyOverloaded = "Overloaded"
	};

	public SettingsStrings Settings { get; } = new()
	{
		Title = "Settings",
		Appearance = "App",
		Theme = "Theme",
		Language = "Language",
		JourneyOptions = "Journeys",
		About = "About",
		ThemeSystem = "System",
		ThemeLight = "Light",
		ThemeDark = "Dark",
		AppearanceTitle = "Appearance",
		AppearanceHint = "Mode, colours and font",
		ModeHeader = "Mode",
		ModeSystemDescription = "Follows the device",
		ModeLightDescription = "Bright surfaces",
		ModeDarkDescription = "Dark surfaces",
		PureBlack = "Pure black in dark mode",
		PureBlackDescription = "Saves power on OLED screens",
		ColorsHeader = "Colours",
		ColorSystem = "System accent colour",
		ColorSystemDescription = "Uses your device's accent colour",
		ColorSystemSolarized = "System accent colour, solarized",
		ColorSystemSolarizedDescription = "System accent on warm solarized surfaces",
		DensityHeader = "Density",
		DensityCompact = "Compact",
		DensityCompactDescription = "More on screen, tighter spacing",
		DensityNormal = "Normal",
		DensityNormalDescription = "Balanced spacing",
		DensityTouch = "Large touch targets",
		DensityTouchDescription = "Taller rows and buttons, more room between them",
		MaterialHeader = "Window material (Windows)",
		MaterialNone = "None",
		MaterialNoneDescription = "Solid colours, no material",
		MaterialMica = "Mica",
		MaterialMicaDescription = "Recommended: a calm base tinted by your wallpaper",
		MaterialMicaAlt = "Mica Alt",
		MaterialMicaAltDescription = "Stronger tint, deeper layering",
		MaterialAcrylic = "Acrylic",
		MaterialAcrylicDescription = "See-through frosted glass (experimental as a whole-window base)",
		MaterialNote = "Pure black surfaces in dark mode replace the material.",
		SurfacesHeader = "Reach of the material",
		SurfacesBackdrop = "Background only",
		SurfacesBackdropDescription = "Cards stay solid on top of the material",
		SurfacesLayered = "Layered cards",
		SurfacesLayeredDescription = "Cards are thin layers over the material",
		SurfacesImmersive = "Immersive",
		SurfacesImmersiveDescription = "Most of the app lets the material show through",
		FontHeader = "Font",
		FontSystem = "System default",
		FontSystemDescription = "The device's own font",
		FontOpenSans = "Open Sans",
		FontOpenSansDescription = "Friendly and neutral",
		FontInterTight = "Inter Tight",
		FontInterTightDescription = "Compact and crisp",
		Animations = "Animations",
		AnimationsDescription =
			"Subtle transitions and effects",
		TechnicalDetails = "Technical details",
		TechnicalDetailsDescription =
			"Show extra detail in notices",
		Results = "Results",
		ResultsDescription = "Journeys per search",
		RequestTimeout = "Request timeout",
		LeadMinutes = "Alert before departure",
		LeadMinutesDescription = "For newly followed journeys: {0} min before departure (changeable per journey)",
		RequestTimeoutDescription = "Give up after {0} s",
		ArriveBy = "Arrive by",
		ArriveByDescription =
			"Open the planner in arrival mode",
		WalkingLegs = "Walking legs",
		WalkingLegsDescription =
			"Show walks in the timeline",
		ExpandNotices = "Expand notices",
		ExpandNoticesDescription =
			"Open journey notices by default",
		ResetJourneySettings = "Reset journey settings",
		JourneyDisplay = "Journey display",
		Occupancy = "Occupancy",
		OccupancyDescription = "Dots showing how full a vehicle is",
		Platforms = "Platforms and tracks",
		PlatformsDescription = "Show Steig and Gleis at stops and interchanges",
		ExpandStops = "Show all stops",
		ExpandStopsDescription = "Open the intermediate stops of every ride",
		ExpertView = "Expert view",
		ExpertViewDescription = "Offer the raw provider data in the journey menu",
		PlaceSearch = "Place search",
		SearchDelay = "Typing pause",
		SearchDelayDescription = "Wait {0} ms after the last keystroke before searching",
		MinQueryLength = "Minimum characters",
		MinQueryLengthDescription = "Search from {0} characters",
		RoutingEntry = "Route preferences",
		RoutingEntryDescription = "Modes, transfers, walking, accessibility",
		VersionPrefix = "DDjourneys {0} ({1})"
	};

	public RoutingStrings Routing { get; } = new()
	{
		Title = "Route preferences",
		Hint = "Applies to the next search.",
		SectionModes = "Modes of transport",
		SectionTransfers = "Transfers",
		SectionWalking = "Walking",
		SectionAccessibility = "Accessibility",
		SectionMore = "More",
		Reset = "Reset route preferences",
		Tram = "Tram",
		CityBus = "City bus",
		IntercityBus = "Regional bus",
		SuburbanRailway = "S-Bahn",
		Train = "Train",
		Cableway = "Cable car",
		Ferry = "Ferry",
		HailedSharedTaxi = "On-demand taxi",
		TransfersUnlimited = "Any number",
		TransfersTwo = "Up to 2",
		TransfersOne = "Up to 1",
		TransfersNone = "Direct only",
		PaceVerySlow = "Very slow",
		PaceSlow = "Slow",
		PaceNormal = "Normal",
		PaceFast = "Fast",
		PaceVeryFast = "Very fast",
		Footpath = "Walk to alternative stops",
		FootpathDescription = "Up to {0} min",
		AlternativeStops = "Nearby stops",
		AlternativeStopsDescription = "Also plan from and to stops close by",
		AccessNone = "No restriction",
		AccessMedium = "Some assistance",
		AccessHigh = "Step-free",
		AvoidStairs = "Avoid stairs",
		AvoidStairsDescription = "Used when no accessibility level is set",
		AvoidEscalators = "Avoid escalators",
		AvoidEscalatorsDescription = "Used when no accessibility level is set",
		FewestTransfers = "Fewest transfers",
		FewestTransfersDescription = "Prefer fewer changes over a faster trip",
		SectionEntrance = "Vehicle entrance",
		EntranceAny = "Any entrance",
		EntranceSmallStep = "Small step at most",
		EntranceNoStep = "Step-free entrance",
		SectionExtraCharge = "Supplements",
		ExtraChargeAny = "No restriction",
		ExtraChargeNone = "Without supplement",
		ExtraChargeLocal = "Local transport only"
	};

	public ProviderStrings Provider { get; } = new()
	{
		Title = "Provider",
		Intro = "Where journeys and stops come from. Each provider covers its own region; changing it clears the current start and destination.",
		InUse = "In use",
		CapJourneys = "Journeys",
		CapPlaces = "Stop search",
		CapContinuation = "Earlier / later",
		CapTracking = "Live tracking",
		CapOccupancy = "Occupancy",
		CapPlatforms = "Platforms",
		CapDepartures = "Departures",
		CapDisruptions = "Disruptions",
		CapNetwork = "Nearby stops, lines, zones",
		CapExtras = "Leg alternatives, PDF",
		CapRouting = "Route preferences",
		Footer = "More providers can be added in future versions."
	};

	public ExpertStrings Expert { get; } = new()
	{
		Open = "Technical details",
		Title = "Expert view",
		Copy = "Copy all",
		Copied = "Copied to clipboard",
		Journey = "Journey",
		Leg = "Ride",
		Stops = "Stop",
		Transfers = "Transfer",
		Hint = "Everything the provider delivered for this journey, including raw codes."
	};

	public TrackingStrings Tracking { get; } = new()
	{
		Title = "Followed journeys",
		Empty = "No followed journeys",
		EmptyHint = "Open a journey and choose \u201cFollow journey\u201d to get live updates.",
		SectionActive = "Active",
		SectionPlanned = "Upcoming",
		SectionRecent = "Completed",
		SectionPaused = "Paused",
		Pause = "Pause",
		Resume = "Resume",
		StopFollowing = "Stop following",
		LiveTitle = "Live notification",
		LiveAutomatic = "Automatic",
		LiveAutomaticHint = "The next journey under way",
		LiveBadge = "Live",
		CourseShow = "Show all stops",
		CourseHide = "Hide stops",
		CourseNotYet = "The stops appear here on the day of travel.",
		CourseWalk = "Walk to {0}",
		CoursePlatform = "Platform {0}",
		CourseTrack = "Track {0}",
		CourseWalkMinutes = "{0} min",
		CourseIn = "in {0} min",
		CourseNow = "now",
		DeleteAll = "Remove all",
		DeleteTitle = "Stop following?",
		DeleteMessage = "This journey will no longer be monitored.",
		DeleteAllMessage = "All followed journeys will be removed.",
		Alerts = "Alerts",
		AlertStart = "Before departure",
		AlertChange = "Changes",
		AlertProblem = "Problems",
		LeadMinutes = "{0} min before departure",
		Periodic = "Repeats",
		NextStop = "Next: {0}",
		Departs = "Departs {0}",
		ArrivedAt = "Arrived {0}",
		PhasePlanned = "Planned",
		PhaseInProgress = "On the way",
		PhaseAtInterchange = "Changing",
		PhaseAtRisk = "Connection at risk",
		PhaseCancelled = "Cancelled",
		PhaseArrived = "Arrived",
		PhasePaused = "Paused",
		FollowedJourneys = "Followed journeys",
		Following = "You are following this journey.",
		FollowFailed = "Journey tracking could not be started: {0}",
		NotificationsDenied = "Notifications are turned off, so live updates will not be shown.",
		ChannelLive = "Live journey",
		ChannelAlerts = "Journey alerts",
		NotifStartsAt = "Journey starts at {0}",
		NotifRoute = "{0} \u2192 {1}",
		NotifRiding = "{0} to {1}",
		NotifNext = "Next: {0} \u00b7 {1}",
		NotifGetOff = "Get off: {0} \u00b7 {1}",
		NotifBoard = "Board {0} \u00b7 {1}",
		NotifChangeTitle = "Change at {0}",
		NotifChangeText = "Next departure {0}",
		NotifRiskTitle = "Connection at risk",
		GuaranteedChange = "guaranteed connection",
		NotifMissedText = "Connection missed at {0}",
		NotifTightText = "Tight change at {0}",
		NotifCancelledTitle = "Journey cancelled",
		NotifArrivedTitle = "Arrived",
		NotifDelay = "+{0} min",
		NotifMonitoring = "Monitoring your journeys",
		NotifActionPause = "Pause",
		NotifActionStop = "Stop",
		NotifStartAlertTitle = "Your journey is about to start",
		NotifStartAlertText = "{0} \u2192 {1}, departs {2}",
		NotifChangeAlertTitle = "Journey updated",
		NotifProblemAlertTitle = "Journey problem",
		NotifMinutes = "{0} min",
		NotifNow = "now"
	};

	public TransportStrings Transport { get; } = new()
	{
		Walk = "Walk",
		Bus = "Bus",
		Tram = "Tram",
		Subway = "Subway",
		SuburbanRail = "Suburban rail",
		RegionalTrain = "Regional train",
		LongDistanceTrain = "Long-distance train",
		Ferry = "Ferry",
		CableCar = "Cable car",
		Taxi = "Taxi",
		OnDemand = "On-demand"
	};
}
