namespace DDjourneys.Localization;

public sealed class EnglishUiStrings : IUiStrings
{
	public CommonStrings Common { get; } = new()
	{
		Ok = "OK",
		Cancel = "Cancel",
		Retry = "Try again",
		Close = "Close",
		Loading = "Loading",
		Searching = "Searching",
		Today = "Today",
		Tomorrow = "Tomorrow",
		Unknown = "Unknown",
		SearchAgain = "Search again",
		TryAgain = "Try again",
		Share = "Share",
		Search = "Search",
		Clear = "Clear",
		SearchFailed = "The search failed.",
		CouldNotReachService = "Could not reach the timetable service.",
		SomethingWentWrong = "Something went wrong.",
		NavigationError = "Navigation error.",
		CouldNotOpenJourney = "Could not open journey."
	};

	public PlanStrings Plan { get; } = new()
	{
		Title = "Where to?",
		FromPlaceholder = "From",
		ToPlaceholder = "To",
		ChooseStart = "Choose start",
		ChooseDestination = "Choose destination",
		ToggleFavouriteFrom = "Toggle favourite for start",
		ToggleFavouriteTo = "Toggle favourite for destination",
		SwapDescription = "Swap start and destination",
		Swap = "\u21c5",
		SearchJourneys = "Search journeys",
		Departure = "Leave",
		Arrival = "Arrive by",
		Date = "Date",
		Time = "Time",
		LeaveNow = "Now",
		Favourites = "Favourites",
		Recent = "Recent places",
		RecentSearches = "Recent searches",
		ShowAllSearches = "Show all {0}",
		ShowFewer = "Show fewer",
		ForgetSearch = "Remove this search",
		SearchAgain = "Search this connection again",
		StartAndDestinationRequired = "Start and destination are required.",
		UseLocationFrom = "Use my location as start",
		UseLocationTo = "Use my location as destination",
		GoHome = "Go home",
		SetHome = "Set home here",
		SaveRoute = "Save route",
		RouteNamePrompt = "Name for this route",
		SavedRoutes = "Saved routes",
		ForgetSavedRoute = "Remove saved route",
		LocationPermissionDenied = "Location access is needed to use your position.",
		LocationUnavailable = "Your position could not be determined.",
		NoStopNearby = "No stop found near your position.",
		PlacesYouSearchForWillAppearHere =
			"Places you search for will appear here."
	};

	public PlaceSearchStrings PlaceSearch { get; } = new()
	{
		Title = "Choose place",
		SearchPlaceholder =
		"Station, stop or address",
		Hint =
		"Type a station, stop or address.",
		TypeAtLeastThreeCharacters =
		"Type at least 3 characters.",
		NoPlacesFound = "No places found.",
		Searching = "Searching...",
		CouldNotReachService =
		"Could not reach the timetable service. Check your connection.",
		SearchForPlace = "Search for a place"
	};

	public ResultsStrings Results { get; } = new()
	{
		Title = "Journeys",
		Loading = "Loading journeys...",
		NoConnections = "No journeys found for this time.",
		JourneysCouldNotBeDisplayed =
			"The journeys could not be displayed.",
		SearchServiceUnavailable =
			"Could not reach the timetable service.",
		PlacesNotUsable =
			"These places can't be used with the selected data provider. Please choose them again.",
		Refresh = "Refresh",
		Retry = "Try again",
		Previous = "Earlier",
		Next = "Later"
	};

	public JourneyStrings Journey { get; } = new()
	{
		Title = "Journey",
		FollowJourney = "Follow journey",
		DeactivateTracking = "Pause tracking",
		Refresh = "Refresh",
		Notes = "Notes",
		NoRealtimeData = "No realtime data",
		ShareJourney = "Share journey",
		NotServed = "Stop cancelled",
		InProgress = "In progress",
		Cancelled = "Cancelled",
		CouldNotBeDisplayed =
			"This journey could not be displayed.",
		ShowOrHideIntermediateStops =
			"Show or hide intermediate stops",
		Walk = "Walk",
		ShareTitle = "Share journey",
		ShareAsText = "As text",
		ShareAsImage = "As image",
		HandOff = "Use this journey",
		HandOffFailed = "The journey could not be passed to the other app.",

		Direct = "Direct",
		OneTransfer = "1 transfer",
		MultipleTransfers = "{0} transfers",
		OneNotice = "1 notice",
		MultipleNotices = "{0} notices",
		AccessibilitySummary =
			"Departs {0}, arrives {1}, {2}, {3}",
		AccessibilityCancelled = ", cancelled",
		AccessibilityArrivalDelay = ", arrival {0}",
		AccessibilityNotices = ", {0}",

		HideStops = "Hide stops",
		OneStop = "1 stop",
		MultipleStops = "{0} stops",
		To = "to",
		ContinueFrom = "continue from",
		ImmediateChange = "Immediate change",
		ToChange = "to change",
		WalkAbout = "Walk about",
		BetweenStops = "between stops",
		ConnectionMayBeMissed = "Connection may be missed",
		ConnectionGuaranteed = "Guaranteed connection: the next vehicle waits",
		NotPossible = "Not possible",
		BlockRideCancelled = "Line {0} is cancelled",
		BlockNotServed = "{0} is not served",
		BlockConnection = "Connection at {0} cannot be reached",
		ConnectionUnreachable = "Connection cannot be reached",
		ChangeAt = "Change at",
		Platform = "Platform",
		WithinStop = "within the stop",
		Track = "Track",
		LowFloor = "Low floor",
		WheelchairAccessible = "Wheelchair accessible",
		BicycleAccessible = "Bicycle accessible",
		Depart = "depart",
		Arrive = "arrive",
		ShowMore = "Show more",
		ShowLess = "Show less",
		ShowFullNotice = "Show the full notice",
		ShowLessNotice = "Show less of the notice",
		Warning = "Warning",
		Notice = "Notice",
		OnTime = "On time",

		// Occupancy strings
		Occupancy = "Occupancy",
		OccupancyVeryLow = "Very few passengers",
		OccupancyLow = "Few passengers",
		OccupancyMedium = "Moderate",
		OccupancyHigh = "Many passengers",
		OccupancyFull = "Full",
		OccupancyOverloaded = "Overloaded"
	};

	public SettingsStrings Settings { get; } = new()
	{
		Title = "Settings",
		Appearance = "App",
		Theme = "Theme",
		Language = "Language",
		JourneyOptions = "Journeys",
		About = "About",
		ThemeSystem = "System",
		ThemeLight = "Light",
		ThemeDark = "Dark",
		AppearanceTitle = "Appearance",
		AppearanceHint = "Mode, colours and font",
		ModeHeader = "Mode",
		ModeSystemDescription = "Follows the device",
		ModeLightDescription = "Bright surfaces",
		ModeDarkDescription = "Dark surfaces",
		PureBlack = "Pure black in dark mode",
		PureBlackDescription = "Saves power on OLED screens",
		ColorsHeader = "Colours",
		ColorSystem = "System accent colour",
		ColorSystemDescription = "Uses your device's accent colour",
		ColorSystemSolarized = "System accent colour, solarized",
		ColorSystemSolarizedDescription = "System accent on warm solarized surfaces",
		DensityHeader = "Density",
		DensityCompact = "Compact",
		DensityCompactDescription = "More on screen, tighter spacing",
		DensityNormal = "Normal",
		DensityNormalDescription = "Balanced spacing",
		DensityTouch = "Large touch targets",
		DensityTouchDescription = "Taller rows and buttons, more room between them",
		MaterialHeader = "Window material (Windows)",
		MaterialNone = "None",
		MaterialNoneDescription = "Solid colours, no material",
		MaterialMica = "Mica",
		MaterialMicaDescription = "Recommended: a calm base tinted by your wallpaper",
		MaterialMicaAlt = "Mica Alt",
		MaterialMicaAltDescription = "Stronger tint, deeper layering",
		MaterialAcrylic = "Acrylic",
		MaterialAcrylicDescription = "See-through frosted glass (experimental as a whole-window base)",
		MaterialNote = "Pure black surfaces in dark mode replace the material.",
		SurfacesHeader = "Reach of the material",
		SurfacesBackdrop = "Background only",
		SurfacesBackdropDescription = "Cards stay solid on top of the material",
		SurfacesLayered = "Layered cards",
		SurfacesLayeredDescription = "Cards are thin layers over the material",
		SurfacesImmersive = "Immersive",
		SurfacesImmersiveDescription = "Most of the app lets the material show through",
		FontHeader = "Font",
		FontSystem = "System default",
		FontSystemDescription = "The device's own font",
		FontOpenSans = "Open Sans",
		FontOpenSansDescription = "Friendly and neutral",
		FontInterTight = "Inter Tight",
		FontInterTightDescription = "Compact and crisp",
		Animations = "Animations",
		AnimationsDescription =
			"Subtle transitions and effects",
		TechnicalDetails = "Technical details",
		TechnicalDetailsDescription =
			"Show extra detail in notices",
		Results = "Results",
		ResultsDescription = "Journeys per search",
		RequestTimeout = "Request timeout",
		LeadMinutes = "Alert before departure",
		LeadMinutesDescription = "For newly followed journeys: {0} min before departure (changeable per journey)",
		RequestTimeoutDescription = "Give up after {0} s",
		ArriveBy = "Arrive by",
		ArriveByDescription =
			"Open the planner in arrival mode",
		WalkingLegs = "Walking legs",
		WalkingLegsDescription =
			"Show walks in the timeline",
		ExpandNotices = "Expand notices",
		ExpandNoticesDescription =
			"Open journey notices by default",
		ResetJourneySettings = "Reset journey settings",
		JourneyDisplay = "Journey display",
		Occupancy = "Occupancy",
		OccupancyDescription = "Dots showing how full a vehicle is",
		Platforms = "Platforms and tracks",
		PlatformsDescription = "Show Steig and Gleis at stops and interchanges",
		ExpandStops = "Show all stops",
		ExpandStopsDescription = "Open the intermediate stops of every ride",
		ExpertView = "Expert view",
		ExpertViewDescription = "Offer the raw provider data in the journey menu",
		PlaceSearch = "Place search",
		SearchDelay = "Typing pause",
		SearchDelayDescription = "Wait {0} ms after the last keystroke before searching",
		MinQueryLength = "Minimum characters",
		MinQueryLengthDescription = "Search from {0} characters",
		RoutingEntry = "Route preferences",
		RoutingEntryDescription = "Modes, transfers, walking, accessibility",
		VersionPrefix = "DDjourneys {0} ({1})"
	};

	public RoutingStrings Routing { get; } = new()
	{
		Title = "Route preferences",
		Hint = "Applies to the next search.",
		SectionModes = "Modes of transport",
		SectionTransfers = "Transfers",
		SectionWalking = "Walking",
		SectionAccessibility = "Accessibility",
		SectionMore = "More",
		Reset = "Reset route preferences",
		Tram = "Tram",
		CityBus = "City bus",
		IntercityBus = "Regional bus",
		SuburbanRailway = "S-Bahn",
		Train = "Train",
		Cableway = "Cable car",
		Ferry = "Ferry",
		HailedSharedTaxi = "On-demand taxi",
		TransfersUnlimited = "Any number",
		TransfersTwo = "Up to 2",
		TransfersOne = "Up to 1",
		TransfersNone = "Direct only",
		PaceVerySlow = "Very slow",
		PaceSlow = "Slow",
		PaceNormal = "Normal",
		PaceFast = "Fast",
		PaceVeryFast = "Very fast",
		Footpath = "Walk to alternative stops",
		FootpathDescription = "Up to {0} min",
		AlternativeStops = "Nearby stops",
		AlternativeStopsDescription = "Also plan from and to stops close by",
		AccessNone = "No restriction",
		AccessMedium = "Some assistance",
		AccessHigh = "Step-free",
		AvoidStairs = "Avoid stairs",
		AvoidStairsDescription = "Used when no accessibility level is set",
		AvoidEscalators = "Avoid escalators",
		AvoidEscalatorsDescription = "Used when no accessibility level is set",
		FewestTransfers = "Fewest transfers",
		FewestTransfersDescription = "Prefer fewer changes over a faster trip"
	};

	public ProviderStrings Provider { get; } = new()
	{
		Title = "Provider",
		Intro = "Where journeys and stops come from. Each provider covers its own region; changing it clears the current start and destination.",
		InUse = "In use",
		CapJourneys = "Journeys",
		CapPlaces = "Stop search",
		CapContinuation = "Earlier / later",
		CapTracking = "Live tracking",
		CapOccupancy = "Occupancy",
		CapPlatforms = "Platforms",
		CapRouting = "Route preferences",
		Footer = "More providers can be added in future versions."
	};

	public ExpertStrings Expert { get; } = new()
	{
		Open = "Technical details",
		Title = "Expert view",
		Copy = "Copy all",
		Copied = "Copied to clipboard",
		Journey = "Journey",
		Leg = "Ride",
		Stops = "Stop",
		Transfers = "Transfer",
		Hint = "Everything the provider delivered for this journey, including raw codes."
	};

	public TrackingStrings Tracking { get; } = new()
	{
		Title = "Followed journeys",
		Empty = "No followed journeys",
		EmptyHint = "Open a journey and choose \u201cFollow journey\u201d to get live updates.",
		SectionActive = "Active",
		SectionPlanned = "Upcoming",
		SectionRecent = "Completed",
		SectionPaused = "Paused",
		Pause = "Pause",
		Resume = "Resume",
		StopFollowing = "Stop following",
		LiveTitle = "Live notification",
		LiveAutomatic = "Automatic",
		LiveAutomaticHint = "The next journey under way",
		LiveBadge = "Live",
		CourseShow = "Show all stops",
		CourseHide = "Hide stops",
		CourseNotYet = "The stops appear here on the day of travel.",
		CourseWalk = "Walk to {0}",
		CoursePlatform = "Platform {0}",
		CourseTrack = "Track {0}",
		CourseWalkMinutes = "{0} min",
		CourseIn = "in {0} min",
		CourseNow = "now",
		DeleteAll = "Remove all",
		DeleteTitle = "Stop following?",
		DeleteMessage = "This journey will no longer be monitored.",
		DeleteAllMessage = "All followed journeys will be removed.",
		Alerts = "Alerts",
		AlertStart = "Before departure",
		AlertChange = "Changes",
		AlertProblem = "Problems",
		LeadMinutes = "{0} min before departure",
		Periodic = "Repeats",
		NextStop = "Next: {0}",
		Departs = "Departs {0}",
		ArrivedAt = "Arrived {0}",
		PhasePlanned = "Planned",
		PhaseInProgress = "On the way",
		PhaseAtInterchange = "Changing",
		PhaseAtRisk = "Connection at risk",
		PhaseCancelled = "Cancelled",
		PhaseArrived = "Arrived",
		PhasePaused = "Paused",
		FollowedJourneys = "Followed journeys",
		Following = "You are following this journey.",
		FollowFailed = "Journey tracking could not be started: {0}",
		NotificationsDenied = "Notifications are turned off, so live updates will not be shown.",
		ChannelLive = "Live journey",
		ChannelAlerts = "Journey alerts",
		NotifStartsAt = "Journey starts at {0}",
		NotifRoute = "{0} \u2192 {1}",
		NotifRiding = "{0} to {1}",
		NotifNext = "Next: {0} \u00b7 {1}",
		NotifGetOff = "Get off: {0} \u00b7 {1}",
		NotifBoard = "Board {0} \u00b7 {1}",
		NotifChangeTitle = "Change at {0}",
		NotifChangeText = "Next departure {0}",
		NotifRiskTitle = "Connection at risk",
		GuaranteedChange = "guaranteed connection",
		NotifMissedText = "Connection missed at {0}",
		NotifTightText = "Tight change at {0}",
		NotifCancelledTitle = "Journey cancelled",
		NotifArrivedTitle = "Arrived",
		NotifDelay = "+{0} min",
		NotifMonitoring = "Monitoring your journeys",
		NotifActionPause = "Pause",
		NotifActionStop = "Stop",
		NotifStartAlertTitle = "Your journey is about to start",
		NotifStartAlertText = "{0} \u2192 {1}, departs {2}",
		NotifChangeAlertTitle = "Journey updated",
		NotifProblemAlertTitle = "Journey problem",
		NotifMinutes = "{0} min",
		NotifNow = "now"
	};

	public TransportStrings Transport { get; } = new()
	{
		Walk = "Walk",
		Bus = "Bus",
		Tram = "Tram",
		Subway = "Subway",
		SuburbanRail = "Suburban rail",
		RegionalTrain = "Regional train",
		LongDistanceTrain = "Long-distance train",
		Ferry = "Ferry",
		CableCar = "Cable car",
		Taxi = "Taxi",
		OnDemand = "On-demand"
	};
}
