namespace DDjourneys.Localization;

public sealed class GermanUiStrings : IUiStrings
{
	public CommonStrings Common { get; } = new()
	{
		Ok = "OK",
		Cancel = "Abbrechen",
		Retry = "Erneut versuchen",
		Close = "Schlie\u00dfen",
		Loading = "L\u00e4dt",
		Searching = "Suche",
		Today = "Heute",
		Tomorrow = "Morgen",
		Unknown = "Unbekannt",
		SearchAgain = "Erneut suchen",
		TryAgain = "Erneut versuchen",
		Share = "Teilen",
		Search = "Suchen",
		Clear = "Leeren",
		SearchFailed = "Die Suche ist fehlgeschlagen.",
		CouldNotReachService =
			"Der Fahrplandienst ist nicht erreichbar.",
		SomethingWentWrong = "Etwas ist schiefgelaufen.",
		NavigationError = "Navigationsfehler.",
		CouldNotOpenJourney = "Verbindung konnte nicht ge\u00f6ffnet werden."
	};

	public PlanStrings Plan { get; } = new()
	{
		Title = "Wohin?",
		FromPlaceholder = "Von",
		ToPlaceholder = "Nach",
		ChooseStart = "Start w\u00e4hlen",
		ChooseDestination = "Ziel w\u00e4hlen",
		ToggleFavouriteFrom =
			"Start als Favorit umschalten",
		ToggleFavouriteTo =
			"Ziel als Favorit umschalten",
		SwapDescription = "Start und Ziel tauschen",
		Swap = "\u21c5",
		SearchJourneys = "Verbindungen suchen",
		Departure = "Abfahrt",
		Arrival = "Ankunft bis",
		Date = "Datum",
		Time = "Zeit",
		LeaveNow = "Jetzt",
		Favourites = "Favoriten",
		Recent = "Zuletzt gesucht",
		RecentSearches = "Letzte Suchen",
		ShowAllSearches = "Alle {0} anzeigen",
		ShowFewer = "Weniger anzeigen",
		ForgetSearch = "Diese Suche entfernen",
		SearchAgain = "Diese Verbindung erneut suchen",
		StartAndDestinationRequired =
			"Start und Ziel sind erforderlich.",
		UseLocationFrom = "Meinen Standort als Start verwenden",
		UseLocationTo = "Meinen Standort als Ziel verwenden",
		GoHome = "Nach Hause",
		SetHome = "Zuhause ändern",
		SaveRoute = "Verbindung speichern",
		RouteNamePrompt = "Name für diese Verbindung",
		SavedRoutes = "Gespeicherte Verbindungen",
		ForgetSavedRoute = "Gespeicherte Verbindung entfernen",
		RouteSaved = "Verbindung gespeichert",
		RouteRemoved = "Verbindung aus den gespeicherten entfernt",
		LocationPermissionDenied = "Für den Standort wird die Berechtigung benötigt.",
		LocationUnavailable = "Der Standort konnte nicht bestimmt werden.",
		NoStopNearby = "Keine Haltestelle in der Nähe gefunden.",
		Via = "Über",
		AddVia = "Zwischenhalt hinzufügen",
		ClearVia = "Zwischenhalt entfernen",
		PlacesYouSearchForWillAppearHere =
			"Gesuchte Orte erscheinen hier."
	};

	public DeparturesStrings Departures { get; } = new()
	{
		Title = "Abfahrten",
		Stop = "Haltestelle",
		ChooseStop = "Haltestelle wählen",
		DeparturesTab = "Abfahrten",
		ArrivalsTab = "Ankünfte",
		Now = "Jetzt",
		NoDepartures = "Keine Abfahrten gefunden.",
		Lines = "Linien an dieser Haltestelle",
		ShowLines = "Linien anzeigen",
		HideLines = "Linien ausblenden",
		Nearby = "Haltestellen in der Nähe",
		UseMyLocation = "Meinen Standort verwenden",
		TariffZone = "Tarifzone {0}",
		Metres = "{0} m",
		Cancelled = "Fällt aus",
		RouteChanges = "Für diese Fahrt gibt es Änderungen",
		Refresh = "Aktualisieren",
		Updated = "Aktualisiert {0}",
		Hint = "Wähle eine Haltestelle, um die nächsten Abfahrten zu sehen.",
		RunTitle = "Fahrtverlauf",
		NoRun = "Für diese Fahrt ist kein Verlauf verfügbar.",
		VehicleHere = "Fahrzeug ist hier",
		OpenDepartures = "Abfahrten an dieser Haltestelle"
	};

	public DisruptionsStrings Disruptions { get; } = new()
	{
		Title = "Störungen",
		OnlyShortTerm = "Nur kurzfristige",
		FilterPlaceholder = "Nach Linie filtern",
		None = "Keine Änderungen im Fahrplan.",
		Planned = "Geplant",
		ShortTerm = "Kurzfristig",
		AffectsRouting = "In der Verbindungssuche berücksichtigt",
		From = "Ab {0}",
		Until = "Bis {0}",
		Range = "{0} \u2013 {1}",
		Notices = "Hinweise",
		ShowAll = "Alle Änderungen anzeigen",
		Selected = "Es werden die Änderungen der gewählten Fahrt angezeigt.",
		Refresh = "Aktualisieren",
		Details = "Details"
	};

	// <extras>
	public ExtrasStrings Extras { get; } = new()
	{
		KindStop = "Haltestelle",
		KindAddress = "Adresse",
		KindPoi = "Sehenswürdigkeit / Ort",
		SearchAddresses = "Adressen",
		SearchAddressesDescription = "Adressen in der Ortssuche finden. Die Verbindung enthält den Fußweg zur nächsten Haltestelle.",
		SearchPois = "Orte und Sehenswürdigkeiten",
		SearchPoisDescription = "Orte, Gebäude und Sehenswürdigkeiten per Name finden.",
		ExactPosition = "Genau an meinem Standort starten",
		ExactPositionDescription = "„Meinen Standort verwenden“ wählt die Adresse, an der Sie sind, statt der nächsten Haltestelle.",
		LiveTitle = "Fahrzeuge live",
		LiveShow = "Wo ist das Fahrzeug?",
		LineFilterPlaceholder = "Liniennummern, z. B. 11, 3 (leer: alle)",
		LiveStart = "Anzeigen",
		LiveStop = "Anhalten",
		LiveConnecting = "Verbinde…",
		LiveWaiting = "Warte auf eine Position. Viele Fahrzeuge melden sich nur alle ein bis zwei Minuten, das kann dauern.",
		LiveRetry = "Erneut prüfen",
		LiveError = "Die Live-Positionen sind gerade nicht verfügbar.",
		LiveLine = "Linie {0}",
		LiveRun = "Fahrt {0}",
		LiveSecondsAgo = "vor {0} s",
		LiveMinutesAgo = "vor {0} min",
		LiveOnTime = "Pünktlich",
		LiveSourceGps = "GPS",
		LiveSourceTelegram = "Funktelegramm",
		LiveHint = "Die Positionen stammen aus dem Community-Netz TLMS und können unvollständig sein.",
		LiveOpenMap = "Karte öffnen",
		AccessTitle = "Barrierefreiheit der Haltestelle",
		AccessHide = "Barrierefreiheit ausblenden",
		AccessNone = "Für diese Haltestelle veröffentlicht die Stadt keine Barrierefreiheitsdaten.",
		AccessPlatform = "Steig {0}",
		AccessBoarding = "Einstieg: {0}",
		AccessKerb = "Bordhöhe: {0}",
		AccessWidth = "Breite: {0}",
		AccessTactile = "Leitsystem: {0}",
		AccessAudio = "Ansagen: {0}",
		ServiceShow = "DVB-Servicestellen in der Nähe",
		ServiceHide = "Servicestellen ausblenden",
		ServiceNone = "Keine Servicestellen in der Nähe.",
		ServiceNeedsPosition = "Zuerst eine Haltestelle wählen oder den Standort verwenden.",
		CapLive = "Fahrzeuge live",
		CapOpenData = "Offene Stadtdaten",
		CapFares = "Preise",
		CapOptimisation = "Routenoptimierung",
		OptSection = "Route optimieren auf",
		OptFastest = "Schnellste Verbindung",
		OptFewestChanges = "Wenigste Umstiege",
		OptLeastWalking = "Wenigster Fußweg",
		OptLowestFare = "Niedrigster Preis",
		OptNote = "Gilt für die nächste Suche bei diesem Anbieter.",
		FaresTitle = "Tickets und Preise",
		FareSingle = "Einzelfahrt",
		FareDay = "Tageskarte",
		FareZones = "Tarifzonen",
		FareValidFor = "Für",
		FareNotAll = "Preise des Anbieters für diese Verbindung. Weitere Tickets (Wochen-, Monats-, ermäßigte Karten, Deutschland-Ticket) liefert seine Antwort nicht.",
		ShortcutHome = "Bring mich nach Hause",
		ShortcutDepartures = "Abfahrten von hier",
		ShortcutNoHome = "Lege zuerst dein Zuhause fest: im Planer auswählen.",
		FaresExpand = "Alle Tickets anzeigen",
		FaresCollapse = "Tickets ausblenden",
		PassengerAdult = "Erwachsene",
		PassengerYouth = "Jugendliche",
		PassengerChild = "Kinder",
		PassengerSenior = "Senioren",
		PassengerDisabled = "Menschen mit Behinderung",
		RunsOn = "Verkehrt {0}",
		RunsDaily = "Verkehrt täglich",
		VehicleReported = "Fahrzeug (gemeldete Position)",
		PdfFailed = "Das PDF konnte nicht geladen werden. Details stehen in der Protokolldatei diagnostics.log.",
		LiveHowTitle = "So funktioniert's",
		LiveHowText = "Eine oder mehrere Liniennummern durch Komma getrennt eingeben (zum Beispiel 3, 11); leer lassen, um alle Fahrzeuge zu sehen. Dann auf Anzeigen tippen: Die Fahrzeuge erscheinen auf der Karte und in der Liste und bewegen sich mit jeder neuen Position. Ein Fahrzeug in der Liste antippen, um es auf der Karte zu finden.",
		LineFilterLabel = "Liniennummern (optional)",
		LiveInvalid = "Ignoriert, keine Liniennummer: {0}",
		LiveEmpty = "Weiterhin keine Positionen. Der TLMS-Dienst könnte gestört sein, kein Fahrzeug dieser Linien meldet gerade eine Position, oder es ist keines unterwegs. Andere Linien probieren oder das Feld leer lassen.",
		LiveCount = "{0} Fahrzeuge",
		MapTitle = "Karte",
		MapShow = "Auf der Karte zeigen",
		MapKeyMissing = "Die Karte braucht Ihren eigenen CARTO-API-Schlüssel. Sie können ihn in den Einstellungen eintragen.",
		MapKeyInvalid = "CARTO hat den API-Schlüssel nicht akzeptiert, deshalb ist die Karte aus. Sie können ihn in den Einstellungen prüfen.",
		MapKeyOpenSettings = "Einstellungen öffnen",
		MapUnsupported = "Dieses Gerät kann die Karte nicht darstellen. Es braucht OpenGL ES 3 und ein aktuelles Android System WebView (Chrome 80 oder neuer). Ein Update des WebView im Play Store kann helfen; der Rest der App ist nicht betroffen.",
		MapCrashed = "Die Anzeige der Karte hat die App beim letzten Mal beendet, deshalb ist die Karte abgeschaltet. Den API-Schlüssel in den Einstellungen erneut zu speichern versucht es noch einmal.",
		MapPickStart = "Start wählen",
		MapPickEnd = "Ziel wählen",
		MapPickStop = "Haltestelle wählen",
		MapPickOnMap = "Auf der Karte wählen",
		MapZoomHint = "Zum Anzeigen der Haltestellen hineinzoomen",
		MapPickHint = "Haltestelle oder Punkt auf der Karte antippen",
		MapStopDepartures = "Abfahrten hier",
		MapJourneyToHere = "Fahrt hierher",
		MapJourneyFromHere = "Fahrt von hier",
		MapUsePlace = "Diesen Ort verwenden",
		MapNothingHere = "Hier wurde keine Adresse oder Haltestelle gefunden",
		MapJourneyTitle = "Karte der Verbindung",
		MapStopTitle = "Haltestellen in der Nähe",
		MapNoData = "Dafür liegen keine Positionen für eine Karte vor.",
		MapStart = "Start",
		MapEnd = "Ziel",
		RunDeparted = "Dieses Fahrzeug ist bereits abgefahren; der Verlauf ist nicht mehr verfügbar.",
		MapAutoFit = "Auto-Ausschnitt",
		MapFitNow = "Alles anzeigen",
		MapInfo = "Kartendaten",
		TrackFollowing = "Folge Linie {0} {1}",
		TrackNotFound = "Weiterhin keine Position von diesem Fahrzeug. Der TLMS-Dienst könnte gestört sein, das Fahrzeug offline sein oder keine Funktelegramme senden, oder die Fahrt hat noch nicht begonnen oder ist schon vorbei.",
		TrackNoCourse = "Diese Fahrt lässt sich nicht live verfolgen: Der Anbieter liefert weder Haltestellenpositionen noch eine Streckengeometrie dafür.",
		TrackShowAll = "Alle Fahrzeuge der Linie zeigen",
		TrackOnlyThisRun = "Nur diese Fahrt wird gezeigt, mit ihrem gesamten Verlauf.",
		NoticeClose = "Schließen",
		NoticeImageFailed = "Das Bild konnte nicht geladen werden.",
		NoticeEmpty = "Diese Meldung enthält keinen weiteren Text.",
		NoticeLinkFailed = "Dieser Link konnte nicht geöffnet werden.",
		AroundTitle = "Rund um die Haltestelle",
		LinesTitle = "Linien an dieser Haltestelle",
		LinesCount = "{0} Linien",
		ServiceTitle = "Servicestellen",
		ServiceHint = "Fahrkartenautomaten und Kundenzentren in der Nähe",
		ServiceCount = "{0} in der Nähe",
		AccessHint = "Einstiegshöhe, Blindenleitsystem, Sprachansage",
		MapSummary = "Haltestelle, Haltestellen in der Nähe und geöffnete Bereiche auf der Karte",
		LiveSummary = "Wo die Fahrzeuge einer Linie gerade sind",
		HomeTitle = "Zuhause",
		HomeNotSet = "Nicht festgelegt: Tippen zum Auswählen"
	};
	// </extras>

	public PlaceSearchStrings PlaceSearch { get; } = new()
	{
		Title = "Ort wählen",
		SearchPlaceholder =
			"Bahnhof, Haltestelle oder Adresse",
		Hint =
			"Bahnhof, Haltestelle oder Adresse eingeben.",
		TypeAtLeastThreeCharacters =
			"Mindestens 3 Zeichen eingeben.",
		NoPlacesFound = "Keine Orte gefunden.",
		Searching = "Suche...",
		CouldNotReachService =
			"Der Fahrplandienst ist nicht erreichbar. Verbindung prüfen.",
		SearchForPlace = "Nach einem Ort suchen"
	};

	public ResultsStrings Results { get; } = new()
	{
		Title = "Verbindungen",
		Loading = "Verbindungen werden geladen...",
		NoConnections =
		"Für diese Zeit wurden keine Verbindungen gefunden.",
		JourneysCouldNotBeDisplayed =
		"Die Verbindungen konnten nicht angezeigt werden.",
		SearchServiceUnavailable =
		"Der Fahrplandienst ist nicht erreichbar.",
		PlacesNotUsable =
		"Diese Orte lassen sich mit dem gewählten Datenanbieter nicht verwenden. Wähle sie bitte neu aus.",
		Refresh = "Aktualisieren",
		Retry = "Erneut versuchen",
		Previous = "Früher",
		Next = "Später"
	};

	public JourneyStrings Journey { get; } = new()
	{
		LegEarlier = "Früher",
		LegLater = "Später",
		LegEarlierHint = "Frühere Alternative für diese Fahrt suchen",
		LegLaterHint = "Spätere Alternative für diese Fahrt suchen",
		LegNone = "Keine Alternative für diese Fahrt gefunden.",
		OpenPdf = "Als PDF öffnen",
		AlternativeShown = "Eine alternative Verbindung wird angezeigt. Neu suchen, um zurückzukehren.",
		Title = "Verbindung",
		FollowJourney = "Verbindung verfolgen",
		DeactivateTracking = "Verfolgung pausieren",
		Refresh = "Aktualisieren",
		Notes = "Hinweise",
		NoRealtimeData = "Keine Echtzeitdaten",
		ShareJourney = "Verbindung teilen",
		NotServed = "Halt f\u00e4llt aus",
		InProgress = "Unterwegs",
		Cancelled = "Ausgefallen",
		CouldNotBeDisplayed =
			"Diese Verbindung konnte nicht angezeigt werden.",
		ShowOrHideIntermediateStops =
			"Zwischenhalte ein- oder ausblenden",
		Walk = "Zu Fu\u00df",
		ShareTitle = "Verbindung teilen",
		ShareAsText = "Als Text",
		ShareAsImage = "Als Bild",
		HandOff = "Diese Verbindung \u00FCbernehmen",
		HandOffFailed = "Die Verbindung konnte nicht an die andere App \u00FCbergeben werden.",

		Direct = "Direkt",
		OneTransfer = "1 Umstieg",
		MultipleTransfers = "{0} Umstiege",
		OneNotice = "1 Hinweis",
		MultipleNotices = "{0} Hinweise",
		AccessibilitySummary =
			"Abfahrt {0}, Ankunft {1}, {2}, {3}",
		AccessibilityCancelled = ", ausgefallen",
		AccessibilityArrivalDelay = ", Ankunft {0}",
		AccessibilityNotices = ", {0}",

		HideStops = "Haltestellen ausblenden",
		OneStop = "1 Halt",
		MultipleStops = "{0} Halte",
		To = "nach",
		ContinueFrom = "weiter ab",
		ImmediateChange = "Sofortiger Umstieg",
		ToChange = "zum Umsteigen",
		WalkAbout = "Etwa zu Fu\u00df",
		BetweenStops = "zwischen Haltestellen",
		ConnectionMayBeMissed =
			"Anschluss kann verpasst werden",
		NotPossible = "Nicht m\u00f6glich",
		BlockRideCancelled = "Linie {0} f\u00e4llt aus",
		BlockNotServed = "{0} wird nicht bedient",
		BlockConnection = "Anschluss in {0} nicht erreichbar",
		ConnectionGuaranteed =
			"Gesicherter Anschluss: Das n\u00e4chste Fahrzeug wartet",
		ConnectionUnreachable = "Anschluss nicht erreichbar",
		ChangeAt = "Umstieg bei",
		Platform = "Steig",
		WithinStop = "innerhalb der Haltestelle",
		Track = "Gleis",
		LowFloor = "Niederflur",
		WheelchairAccessible =
			"Rollstuhlgerecht",
		BicycleAccessible =
			"Fahrradmitnahme m\u00f6glich",
		Depart = "Abfahrt",
		Arrive = "Ankunft",
		ShowMore = "Mehr anzeigen",
		ShowLess = "Weniger anzeigen",
		ShowFullNotice = "Den vollst\u00e4ndigen Hinweis anzeigen",
		ShowLessNotice = "Hinweis einklappen",
		Warning = "Warnung",
		Notice = "Hinweis",
		OnTime = "P\u00fcnktlich",

		// Occupancy strings
		Occupancy = "Auslastung",
		OccupancyVeryLow = "Sehr wenige Fahrgäste",
		OccupancyLow = "Wenige Fahrgäste",
		OccupancyMedium = "Mittel",
		OccupancyHigh = "Viele Fahrgäste",
		OccupancyFull = "Voll",
		OccupancyOverloaded = "Überfüllt"
	};

	public SettingsStrings Settings { get; } = new()
	{
		Title = "Einstellungen",
		Appearance = "App",
		Theme = "Design",
		Language = "Sprache",
		JourneyOptions = "Verbindungen",
		MapSection = "Karte",
		MapKeyTitle = "CARTO-API-Schlüssel",
		MapKeyDescription = "Die Grundkarte stammt von CARTO und braucht Ihren eigenen Schlüssel. Ohne gültigen Schlüssel bleibt die Karte aus.",
		MapKeyPlaceholder = "Schlüssel hier einfügen",
		MapKeySave = "Schlüssel verwenden",
		MapKeyStatusMissing = "Kein Schlüssel: die Karte ist aus",
		MapKeyStatusInvalid = "CARTO hat diesen Schlüssel nicht akzeptiert",
		MapKeyStatusSet = "Schlüssel gespeichert",
		About = "Über DDjourneys",
		ThemeSystem = "System",
		ThemeLight = "Hell",
		ThemeDark = "Dunkel",
		AppearanceTitle = "Darstellung",
		AppearanceHint = "Modus, Farben und Schrift",
		ModeHeader = "Modus",
		ModeSystemDescription = "Folgt dem Ger\u00e4t",
		ModeLightDescription = "Helle Fl\u00e4chen",
		ModeDarkDescription = "Dunkle Fl\u00e4chen",
		PureBlack = "Reines Schwarz im Dunkelmodus",
		PureBlackDescription = "Spart Strom auf OLED-Displays",
		ColorsHeader = "Farben",
		ColorSystem = "Systemakzentfarbe",
		ColorSystemDescription = "\u00dcbernimmt die Akzentfarbe Deines Ger\u00e4ts",
		ColorSystemSolarized = "Systemakzentfarbe, Solarized",
		ColorSystemSolarizedDescription = "Systemakzent auf warmen Solarized-Fl\u00e4chen",
		DensityHeader = "Dichte",
		DensityCompact = "Kompakt",
		DensityCompactDescription = "Mehr auf dem Bildschirm, engere Abst\u00e4nde",
		DensityNormal = "Normal",
		DensityNormalDescription = "Ausgewogene Abst\u00e4nde",
		DensityTouch = "Gro\u00dfe Touch-Fl\u00e4chen",
		DensityTouchDescription = "H\u00f6here Zeilen und Schaltfl\u00e4chen, mehr Platz dazwischen",
		MaterialHeader = "Fenstermaterial (Windows)",
		MaterialNone = "Keines",
		MaterialNoneDescription = "Volle Farben, kein Material",
		MaterialMica = "Mica",
		MaterialMicaDescription = "Empfohlen: ruhiger Untergrund, vom Hintergrundbild get\u00f6nt",
		MaterialMicaAlt = "Mica Alt",
		MaterialMicaAltDescription = "St\u00e4rkere T\u00f6nung, tiefere Ebenen",
		MaterialAcrylic = "Acryl",
		MaterialAcrylicDescription = "Durchscheinendes Milchglas (als Fensterbasis experimentell)",
		MaterialNote = "Reines Schwarz im dunklen Modus ersetzt das Material.",
		SurfacesHeader = "Reichweite des Materials",
		SurfacesBackdrop = "Nur Hintergrund",
		SurfacesBackdropDescription = "Karten bleiben deckend auf dem Material",
		SurfacesLayered = "Karten als Ebenen",
		SurfacesLayeredDescription = "Karten sind d\u00fcnne Ebenen \u00fcber dem Material",
		SurfacesImmersive = "Immersiv",
		SurfacesImmersiveDescription = "Das Material scheint fast \u00fcberall durch",
		FontHeader = "Schrift",
		FontSystem = "Systemstandard",
		FontSystemDescription = "Die Schrift des Ger\u00e4ts",
		FontOpenSans = "Open Sans",
		FontOpenSansDescription = "Freundlich und neutral",
		FontInterTight = "Inter Tight",
		FontInterTightDescription = "Kompakt und klar",
		Animations = "Animationen",
		AnimationsDescription =
			"Unaufdringliche \u00dcberg\u00e4nge und Effekte",
		TechnicalDetails = "Technische Details",
		TechnicalDetailsDescription =
			"Technische Ursache bei Fehlern und Hinweisen anzeigen",
		Results = "Ergebnisse",
		ResultsDescription = "Verbindungen pro Suche",
		RequestTimeout = "Zeitlimit",
		LeadMinutes = "Hinweis vor Abfahrt",
		LeadMinutesDescription = "F\u00fcr neu verfolgte Verbindungen: {0} Min. vor Abfahrt (je Verbindung \u00e4nderbar)",
		RequestTimeoutDescription = "Abbruch nach {0} s",
		ArriveBy = "Ankunft bis",
		ArriveByDescription =
			"Planer im Ankunftsmodus \u00f6ffnen",
		WalkingLegs = "Fu\u00dfwege",
		WalkingLegsDescription =
			"Fu\u00dfwege in der Zeitlinie anzeigen",
		ExpandNotices = "Hinweise ausklappen",
		ExpandNoticesDescription =
			"Verbindungshinweise standardm\u00e4\u00dfig \u00f6ffnen",
		ResetJourneySettings =
			"Verbindungseinstellungen zur\u00fccksetzen",
		JourneyDisplay = "Verbindungsanzeige",
		Occupancy = "Auslastung",
		OccupancyDescription = "Punkte in den Verbindungsdetails zeigen, wie voll ein Fahrzeug ist",
		Platforms = "Steige und Gleise",
		PlatformsDescription = "Steig- und Gleisnummern in den Verbindungsdetails anzeigen",
		ExpandStops = "Alle Halte zeigen",
		ExpandStopsDescription = "Zwischenhalte jeder Fahrt aufgeklappt anzeigen",
		ExpertView = "Expertenansicht",
		ExpertViewDescription = "Rohdaten des Anbieters im Verbindungsmenü anbieten",
		DeveloperOptions = "Entwickleroptionen",
		DeveloperOptionsDescription = "Diagnosewerkzeuge. Ausschalten löscht auch die Protokolldatei",
		LogToFile = "In Datei protokollieren",
		LogToFileDescription = "Jede Anfrage und Antwort der Anbieter aufzeichnen. Aus: es wird nichts geschrieben",
		ShareLog = "Protokolldatei teilen",
		ClearLog = "Protokolldatei löschen",
		PlaceSearch = "Ortssuche",
		SearchDelay = "Tipppause",
		SearchDelayDescription = "Nach der letzten Eingabe {0} ms warten, dann suchen",
		MinQueryLength = "Mindestzeichen",
		MinQueryLengthDescription = "Suche ab {0} Zeichen",
		RoutingEntry = "Routenpräferenzen",
		RoutingEntryDescription = "Verkehrsmittel, Umstiege, Gehen, Barrierefreiheit",
		StartEntry = "Start im Eingabemodus",
		StartEntryDescription = "Direkt die Zielsuche öffnen",
		StartTitle = "Start",
		StartInputMode = "Im Eingabemodus öffnen",
		StartInputModeDescription = "Die App öffnet mit ausgefülltem Start und bereiter Zielsuche.",
		StartFromTitle = "Start der Fahrt",
		StartFromLocation = "Mein Standort",
		StartFromLocationDescription = "Die Haltestelle oder Adresse in deiner Nähe",
		StartFromPlace = "Ein Ort",
		StartFromPlaceDescription = "Eine Haltestelle, ein POI oder eine Adresse",
		StartPlaceNone = "Ort auswählen",
		StartPlaceHint = "Der Ort wird je Anbieter gemerkt. Ohne Ort wird dein Standort verwendet.",
		VersionPrefix = "DDjourneys {0} ({1})",
		AboutEntryDescription = "Was die App kann und wie man sie benutzt",
		InterfaceVersions = "Schnittstellenversionen",
		InterfaceVersionsDescription = "Die Versionen aller Schnittstellen dieser Version: Dienste, gespeicherte Daten und Contract. Gehören in jeden Fehlerbericht.",
		CopyInterfaces = "Versionen kopieren",
		InterfacesCopied = "In die Zwischenablage kopiert"
	};

	public RoutingStrings Routing { get; } = new()
	{
		Title = "Routenpräferenzen",
		Hint = "Gilt für die nächste Suche.",
		SectionModes = "Verkehrsmittel",
		SectionTransfers = "Umstiege",
		SectionWalking = "Gehen",
		SectionAccessibility = "Barrierefreiheit",
		SectionMore = "Weiteres",
		Reset = "Routenpräferenzen zurücksetzen",
		Tram = "Straßenbahn",
		CityBus = "Stadtbus",
		IntercityBus = "Regionalbus",
		SuburbanRailway = "S-Bahn",
		Train = "Zug",
		Cableway = "Seilbahn",
		Ferry = "Fähre",
		HailedSharedTaxi = "Anrufsammeltaxi",
		TransfersUnlimited = "Beliebig viele",
		TransfersTwo = "Bis zu 2",
		TransfersOne = "Bis zu 1",
		TransfersNone = "Nur direkt",
		PaceVerySlow = "Sehr langsam",
		PaceSlow = "Langsam",
		PaceNormal = "Normal",
		PaceFast = "Schnell",
		PaceVeryFast = "Sehr schnell",
		Footpath = "Weg zu Ausweichhalten",
		FootpathDescription = "Bis zu {0} Min.",
		AlternativeStops = "Nahe Haltestellen",
		AlternativeStopsDescription = "Auch von und zu Haltestellen in der Nähe planen",
		AccessNone = "Keine Einschränkung",
		AccessMedium = "Etwas Unterstützung",
		AccessHigh = "Stufenfrei",
		AvoidStairs = "Treppen meiden",
		AvoidStairsDescription = "Gilt, wenn keine Barrierefreiheitsstufe gewählt ist",
		AvoidEscalators = "Rolltreppen meiden",
		AvoidEscalatorsDescription = "Gilt, wenn keine Barrierefreiheitsstufe gewählt ist",
		FewestTransfers = "Wenigste Umstiege",
		FewestTransfersDescription = "Weniger Umstiege vor schnellerer Fahrt",
		SectionEntrance = "Fahrzeugeinstieg",
		SectionTickets = "Tickets für",
		EntranceAny = "Beliebiger Einstieg",
		EntranceSmallStep = "Höchstens kleine Stufe",
		EntranceNoStep = "Stufenloser Einstieg",
		SectionExtraCharge = "Zuschläge",
		ExtraChargeAny = "Keine Einschränkung",
		ExtraChargeNone = "Ohne Zuschlag",
		ExtraChargeLocal = "Nur Nahverkehr"
	};

	public ProviderStrings Provider { get; } = new()
	{
		Title = "Anbieter",
		Intro = "Woher Verbindungen und Haltestellen kommen. Jeder Anbieter deckt seine eigene Region ab; ein Wechsel setzt Start und Ziel zurück.",
		InUse = "Aktiv",
		Use = "Diesen Anbieter verwenden",
		Experimental = "Experimentell",
		CapJourneys = "Verbindungen",
		CapPlaces = "Haltestellensuche",
		CapContinuation = "Früher / später",
		CapTracking = "Live-Verfolgung",
		CapOccupancy = "Auslastung",
		CapPlatforms = "Steige und Gleise",
		CapDepartures = "Abfahrten",
		CapDisruptions = "Störungen",
		CapNetwork = "Haltestellen, Linien, Zonen",
		CapExtras = "Alternativen, PDF",
		CapRouting = "Routenpräferenzen",
		Footer = "Weitere Anbieter können in künftigen Versionen folgen."
	};

	public ExpertStrings Expert { get; } = new()
	{
		Open = "Technische Details",
		Title = "Expertenansicht",
		Copy = "Alles kopieren",
		Copied = "In die Zwischenablage kopiert",
		Journey = "Verbindung",
		Leg = "Fahrt",
		Stops = "Halt",
		Transfers = "Umstieg",
		Hint = "Alles, was der Anbieter zu dieser Verbindung geliefert hat, einschließlich Rohwerten."
	};

	public TrackingStrings Tracking { get; } = new()
	{
		Title = "Verfolgte Verbindungen",
		Empty = "Keine verfolgten Verbindungen",
		EmptyHint = "\u00d6ffne eine Verbindung und w\u00e4hle \u201eVerbindung verfolgen\u201c, um Live-Updates zu erhalten.",
		SectionActive = "Aktiv",
		SectionPlanned = "Bevorstehend",
		SectionRecent = "Abgeschlossen",
		SectionPaused = "Pausiert",
		Pause = "Pausieren",
		Resume = "Fortsetzen",
		StopFollowing = "Nicht mehr verfolgen",
		DismissNotice = "Hinweis ausblenden",
		NoticeHistory = "Alle Meldungen",
		LiveTitle = "Live-Benachrichtigung",
		LiveAutomatic = "Automatisch",
		LiveAutomaticHint = "Die n\u00e4chste laufende Fahrt",
		LiveBadge = "Live",
		CourseShow = "Alle Halte anzeigen",
		CourseHide = "Halte ausblenden",
		CourseNotYet = "Die Halte erscheinen hier am Reisetag.",
		CourseWalk = "Fu\u00dfweg nach {0}",
		CoursePlatform = "Steig {0}",
		CourseTrack = "Gleis {0}",
		ShowOnMap = "Fahrzeuge auf der Karte zeigen",
		ToggleDetails = "Details ein- oder ausblenden",
		CourseWalkMinutes = "{0} Min.",
		CourseIn = "in {0} Min.",
		CourseNow = "jetzt",
		DeleteAll = "Alle entfernen",
		DeleteTitle = "Nicht mehr verfolgen?",
		DeleteMessage = "Diese Verbindung wird nicht mehr \u00fcberwacht.",
		DeleteAllMessage = "Alle verfolgten Verbindungen werden entfernt.",
		Alerts = "Hinweise",
		AlertStart = "Vor der Abfahrt",
		AlertChange = "\u00c4nderungen",
		AlertProblem = "Probleme",
		LeadMinutes = "{0} Min. vor Abfahrt",
		Periodic = "Wiederholt sich",
		NextStop = "N\u00e4chster Halt: {0}",
		Departs = "Abfahrt {0}",
		ArrivedAt = "Angekommen {0}",
		PhasePlanned = "Geplant",
		PhaseInProgress = "Unterwegs",
		PhaseAtInterchange = "Umstieg",
		PhaseAtRisk = "Anschluss gef\u00e4hrdet",
		PhaseCancelled = "F\u00e4llt aus",
		PhaseArrived = "Angekommen",
		PhasePaused = "Pausiert",
		FollowedJourneys = "Verfolgte Verbindungen",
		Following = "Du verfolgst diese Verbindung.",
		FollowFailed = "Die Verfolgung konnte nicht gestartet werden: {0}",
		NotificationsDenied = "Benachrichtigungen sind ausgeschaltet, Live-Updates werden daher nicht angezeigt.",
		ChannelLive = "Live-Verbindung",
		ChannelAlerts = "Verbindungshinweise",
		NotifStartsAt = "Fahrt beginnt um {0}",
		NotifRoute = "{0} \u2192 {1}",
		NotifRiding = "{0} nach {1}",
		NotifNext = "N\u00e4chster Halt: {0} \u00b7 {1}",
		NotifGetOff = "Aussteigen: {0} \u00b7 {1}",
		NotifBoard = "Einsteigen: {0} \u00b7 {1}",
		NotifChangeTitle = "Umstieg in {0}",
		NotifWalkFromUntil = "Von {0} bis {1}",
		NotifChangeText = "N\u00e4chste Abfahrt {0}",
		NotifRiskTitle = "Anschluss gef\u00e4hrdet",
		GuaranteedChange = "gesicherter Anschluss",
		NotifMissedText = "Anschluss in {0} verpasst",
		NotifTightText = "Knapper Umstieg in {0}",
		NotifCancelledTitle = "Fahrt f\u00e4llt aus",
		NotifArrivedTitle = "Angekommen",
		NotifDelay = "+{0} Min.",
		NotifMonitoring = "Deine Verbindungen werden \u00fcberwacht",
		NotifActionPause = "Pausieren",
		NotifActionStop = "Beenden",
		NotifStartAlertTitle = "Deine Fahrt beginnt gleich",
		NotifStartAlertText = "{0} \u2192 {1}, Abfahrt {2}",
		NotifChangeAlertTitle = "Fahrt aktualisiert",
		NotifProblemAlertTitle = "Problem auf deiner Fahrt",
		NotifMinutes = "{0} Min.",
		NotifNow = "jetzt"
	};

	public TransportStrings Transport { get; } = new()
	{
		Walk = "Zu Fu\u00df",
		Bus = "Bus",
		Tram = "Stra\u00dfenbahn",
		Subway = "U-Bahn",
		SuburbanRail = "S-Bahn",
		RegionalTrain = "Regionalbahn",
		LongDistanceTrain = "Fernverkehr",
		Ferry = "F\u00e4hre",
		CableCar = "Seilbahn",
		Taxi = "Taxi",
		OnDemand = "On-Demand"
	};

	public WidgetStrings Widgets { get; } = new()
	{
		NameRoute = "Verbindung",
		NameDepartures = "Abfahrten",
		NameArrivals = "Ankünfte",
		NameNearby = "Haltestellen in der Nähe",
		NameNearbyDepartures = "Nächste Abfahrten in der Nähe",
		Here = "Mein Standort",
		Loading = "Aktualisiere…",
		SetUp = "Zum Einrichten tippen",
		NoDepartures = "Keine Abfahrten",
		NoArrivals = "Keine Ankünfte",
		NoJourneys = "Keine Verbindung gefunden",
		NoStopsNearby = "Keine Haltestelle im Umkreis von {0} m",
		NeedsLocation = "Kein Standort verfügbar. App einmal öffnen und Standortzugriff erlauben.",
		RefreshFailed = "Aktualisierung fehlgeschlagen",
		UpdatedAt = "Aktualisiert {0}",
		PositionFrom = "Standort von {0}",
		Meters = "{0} m",
		ConfigTitle = "Widget-Einstellungen",
		ConfigFrom = "Von",
		ConfigTo = "Nach",
		ConfigStop = "Haltestelle",
		ChoosePlace = "Auswählen…",
		SearchHint = "Haltestelle oder Ort suchen",
		NoResults = "Keine Treffer",
		ConfigRadius = "Suchradius",
		ConfigRows = "Zeilen",
		RowsAuto = "So viele wie passen",
		ConfigStops = "Haltestellen",
		ConfigPerStop = "Abfahrten pro Haltestelle",
		ConfigLines = "Nur diese Linien",
		LinesHint = "z. B. 3, 11 (leer: alle)",
		ConfigModes = "Verkehrsmittel",
		ModesAll = "Alle",
		ConfigAuto = "Automatisch aktualisieren",
		ConfigInterval = "Alle",
		IntervalMinutes = "{0} Min.",
		IntervalHours = "{0} Std.",
		ConfigAutoHint = "Android entscheidet, wann ein Widget im Hintergrund aktualisieren darf, höchstens alle 30 Minuten. Zum sofortigen Aktualisieren das Widget antippen.",
		ConfigProvider = "Anbieter",
		ConfigLabelTitle = "Titel",
		ConfigTitleHint = "Leer lässt den Standardtitel",
		ConfigProviderChanged = "Orte des anderen Anbieters wurden entfernt",
		Done = "Fertig",
		LocationHint = "Widgets mit Haltestellen in der Nähe brauchen den Standort. Für Aktualisierungen im Hintergrund den Standortzugriff in den App-Einstellungen dauerhaft erlauben.",
		OpenSettings = "App-Einstellungen öffnen"
	};
}
